[package]
name = "qdx-py"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "qdx_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.1"
qdx-common = { path = "local_dependencies/qdx-common", features = ["serde"], default-features = false  }
serde_json = { version = "1.0.87" }
