[tool.poetry]
name = "quilt-py"
version = "0.10.2"
description = ""
authors = ["Jeremy Berman <jerber@sas.upenn.edu>"]
readme = "README.md"
packages = [{ include = "quilt" }]
exclude = ["tests/**/*"]


[tool.poetry.dependencies]
python = "^3.11"
strawberry-graphql = "*"
pydantic = { extras = ["email"], version = "^1" }
phonenumbers = "*"
devtools = "*"
httpx = "*"
firebase-admin = "*"
sentry-sdk = { extras = ["pure-eval", 'httpx'], version = "*" }

[tool.poetry.group.dev.dependencies]
mypy = "^1.0.0"
pytest = "^7.2.1"
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"