[tool.poetry]
name = "pistacchio-federated-dataset"
version = "0.0.1-15"
description = "A simple library to partition your dataset to perform federated learning"
authors = ["Luca Corbucci"]
license = "MIT"
readme = "README.md"
packages = [ { include = "FederatedDataset" } ]

[tool.poetry.dependencies]
python = "^3.8"
torchvision = "^0.15.1"
numpy = "^1.24.2"
pandas = "^1.5.3"
tqdm = "^4.65.0"
scikit-learn = "^1.2.2"
wandb = "^0.14.0"
pytest = "^7.2.2"
black = "^23.3.0"
google-api-python-client = "^2.86.0"
torch = "2.0.0"
opacus = "1.3"


[tool.poetry.group.dev.dependencies]
black = {extras = ["jupyter"], version = "^22.12.0"}
pytest = "^7.2.1"
coverage = "^7.1.0"
ipykernel = "^6.23.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# --- Black config ------------------------------------------- #

[tool.black]
line-length = 88


[tool.ruff]
line-length = 88
select = ["ALL"]
target-version = "py310"
ignore = [
    "D101",
    "D100",
    "D404",
    "I001",
    "C901",
    "D213",
    "D203",
    "B905",
    "EM101",
    "D205",
    "D407",
    "E501",
    "ANN101",
    "D401",
    "T201",
    "D416",
    "PLR0913"
]
fix = true
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "tests/codegen/snapshots"
]
src = ["pistacchio", "tests"]

