[tool.poetry]
name = "miscellaneous-utils"
version = "0.1.3"
description = ""
authors = ["Nicholas Mischke <nmischkework@proton.me>"]
readme = "README.md"
packages = [{include = "utils"}]
repository = "https://github.com/nicholas-mischke/miscellaneous-utils"

[tool.poetry.dependencies]
python = "^3.7.0"
typer = "0.9.0"

[tool.poetry.group.dev.dependencies]
pytest = "7.3.1"
pytest-cov = "4.0.0"
tox = "4.5.1"
coverage = "7.2.5"

[tool.poetry.scripts]
utils = "utils.commands:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
