[build-system]
requires = ["setuptools>=61.0", "numpy>=1.22", "numba>=0.56", "zarr", "pytest", "pyyaml"]
build-backend = "setuptools.build_meta"

[project]
name = "xengsort"
version = "1.5.0.1"
authors = [
  { name="Jens Zentgraf", email="zentgraf@cs.uni-saarland.de" },
  { name="Sven Rahmann", email="rahmann@cs.uni-saarland.de" }
]
description = "A fast xenograft read sorter based on space-efficient k-mer hashing"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering :: Bio-Informatics"
]

[project.urls]
"Homepage" = "https://gitlab.com/genomeinformatics/xengsort"
"Bug Tracker" = "https://gitlab.com/genomeinformatics/xengsort/issues"