[project]
name = "unipay"
version = "0.1.6"
description = ""
authors = [
    { name = "djkcyl", email = "cyl@cyllive.cn" },
]
dependencies = [
    "fastapi~=0.99.0",
    "qrcode[pil]",
    "peewee",
    "uvicorn",
    "jinja2",
    "python-multipart>=0.0.6",
    "click>=8.1.6",
    "pyzbar>=0.1.9",
    "aiofiles>=23.2.1",
]
requires-python = ">=3.8"
readme = "README.md"

[project.license]
text = "MIT"

[project.scripts]
unipay = "unipay.__main__:main"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm.build]
includes = [
    "unipay",
]
