[tool.poetry]
name = "gmpg"
version = "0.1.20"
description = "tools for metamodern software development"
keywords = ["Git", "Poetry"]
homepage = "https://ragt.ag/code/projects/gmpg"
repository = "https://ragt.ag/code/projects/gmpg.git"
documentation = "https://ragt.ag/code/projects/gmpg/api"
authors = ["Angelo Gladding <angelo@ragt.ag>"]
license = "BSD-2-Clause"

[tool.poetry.scripts]
gmpg = "gmpg.__main__:main"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
black = "^23.7.0"
isort = "^5.11.4"
pendulum = "^2.1.2"
pydeps = "^1.11.0"
pyright = "^1.1.322"
mock = "^5.0.1"
pytest-cov = "^4.0.0"
pytest-pep8 = "^1.0.6"
pytest-gevent = "^1.1.0"
pytest = "^7.4.0"
radon = "^5.1.0"
responses = "^0.22.0"
toml = "^0.10.2"
txtint = ">=0.1"
ipython = "^8.14.0"
pip = "^23.2.1"

[tool.poetry.group.dev.dependencies]
txtint = {path="../txtint", develop=true}

# [[tool.poetry.source]]
# name = "main"
# url = "https://ragt.ag/code/pypi"

[tool.pyright]
reportGeneralTypeIssues = false
reportOptionalMemberAccess = false

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
