[tool.poetry]
name = "pydantic-sarif"
version = "0.1.1"
description = "A pydantic binding library for the sarif standard"
authors = ["JoranHonig <JoranHonig@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
