[package]
name = "polars-error"
version = "0.32.0"
authors = ["Ritchie Vink <ritchie46@gmail.com>"]
edition = "2021"
homepage = "https://www.pola.rs/"
license = "MIT"
repository = "https://github.com/pola-rs/polars"
description = "Error definitions for the Polars DataFrame library"
resolver = "2"

[dependencies]
regex = { version = "1.7.1", optional = true }
thiserror = "1"

[dependencies.arrow ]
package = "arrow2"
# git = "https://github.com/jorgecarleitao/arrow2"
# git = "https://github.com/ritchie46/arrow2"
# rev = "9beabec8cfb5502582d31ab898fdd36e7af0873c"
# path = "../arrow2"
# branch = "duration_json"
version = "0.17.4"
default-features = false
features = [
  "compute_aggregate",
  "compute_arithmetics",
  "compute_boolean",
  "compute_boolean_kleene",
  "compute_cast",
  "compute_comparison",
  "compute_concatenate",
  "compute_filter",
  "compute_if_then_else",
]
