[tool.poetry]
name = "zeka"
version = "0.1.3"
description = ""
authors = ["Niklas Alexander Shern <nshern@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
randomname = "^0.2.1"

[tool.poetry.scripts]
zk = 'zeka.__main__:main'

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
