[tool.poetry]
name = "osm4gpd"
version = "0.2.0a0"
description = "A parser that loads openstreetmaps native protobuf format into a sparse geopandas dataframe."
authors = ["Christian <christian.knauth@citywalx.net>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
pandas = ">=2.0.3"
geopandas = ">=0.13.2"
shapely = ">=2.0.1"
protobuf = ">=4.23.4"
numpy = ">=1.25.1"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
pytest-datadir = "^1.4.1"
pytest-codecov = "^0.5.1"
exceptiongroup = "^1.1.3"


[tool.poetry.group.dev.dependencies]
ipdb = "^0.13.13"
mypy-protobuf = "^3.4.0"
mypy = "^1.4.1"
flake8 = "^6.0.0"
isort = "^5.12.0"
black = "^23.7.0"
bandit = "^1.7.5"
pandas-stubs = "^2.0.3.230814"

[tool.commitizen]
version = "0.2.0a0"
tag_format = "$version"
version_files = [
    "osm4gpd/__version__.py",
    "pyproject.toml:^version"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
