[tool.poetry]
name = "awakatime"
version = "1.1.6"
description = "A simple async wrapper for the Wakatime API"
authors = ["Yan Gabriel <yangabrielogy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = { extras = ["speedups"], version = "^3.8.5" }

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
isort = "^5.12.0"
pytest = "^7.4.0"
pytest-asyncio = "^0.21.1"
pytest-dotenv = "^0.5.2"
pytest-cov = "^4.1.0"

[tool.poetry.group.docs.dependencies]
pydocstyle = "^6.3.0"
mkdocstrings = "^0.22.0"
mkdocstrings-python = "^1.3.0"
mkdocs-material = "^9.1.21"

[tool.black]
line-length = 95

[tool.isort]
profile = "black"
src_paths = ["awakatime"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
env_files = [".env"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
